# Generated by Django 6.1.1 on 2026-10-02 02:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aventura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("detalle", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imagen_url", models.URLField(blank=True, max_length=500, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrdenCacebera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cliente_nombre", models.CharField(max_length=50)),
                ("cliente_email", models.EmailField(max_length=254)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estado", models.CharField(default="APAGADO", max_length=20)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ordendetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "aventura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carroApp.aventura",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="carroApp.ordencacebera",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReciboBoleta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_canje", models.CharField(max_length=32, unique=True)),
                ("instrucciones", models.TextField()),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("total_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "orden",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibo",
                        to="carroApp.ordencacebera",
                    ),
                ),
            ],
        ),
    ]
